default_stages: [commit, push]
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      exclude: ^(venv/|docs/)
      types: ['python']
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args:
        - --max-line-length=88
        - --ignore=F401,E501,W503,E731,E743,E741
      exclude: ^(venv/|docs/)
      types: ['python']
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: ['commit']
      language: system
      entry: /home/ondro/mambaforge/envs/apsg/bin/python -m pytest -s -v .
      types: ['python']
      pass_filenames: false
      always_run: true
